//array of possible quotes
//==============================
var quotes = [
  {quote: "ALWAYS",
  source: "professor severus snape"},
  {quote: "YER A WIZARD, HARRY",
  source: "hagrid"},
  {quote: "avada kedavra",
  source: "HE WHO MUST NOT BE NAMED"},
  {quote: "Me fail english, thats unpossible!",
  source: "Ralph Riggum"},
  {quote: "I typed your symptom into the thing up here, and it says you could have network connectivity problems. ",
  source: "Andy Dywer"},
  {quote: "Be Prepared!",
  source: "Scar"},
  {quote: "He looka like a man",
  source: "Ms Swan"},
  {quote: "Cool Prius!",
  source: "Noone ever"},
  {quote: "I have a dream today",
  source: "Dr. Martin Luther King Jr"},
  {quote: "Hello",
  source: "Benjamin Franklin (Probably)"},
  {quote: "Nope",
  source: "Chuck Testa"},
  {quote: "Ain't nobody got time for that",
  source: "Sweet Brown"},
  {quote: "I've got greens, beans, potatoes, tomatoes, lambs, rams, hogs, dogs, chickens, turkeys... You name it!",
  source: "Shirley Caesar"},
  {quote: "Who is you?",
  source: "Rachel EB Wilson"},
  {quote: "ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn",
  source: "Whispers"}
];